source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'pry'
gem 'pry-nav'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3', '~>1.3.6'
gem 'tux'
